import bcrypt from 'bcryptjs'
import User from '../models/User.js'
import Listing from '../models/Listing.js'

export const SEED_LISTINGS = [
  {
    title: 'Beach shack near Palolem',
    location: 'Goa',
    pricePerNight: 3200,
    maxGuests: 4,
    amenities: ['WiFi', 'Beach access'],
    description: 'Sandy path to Palolem beach. Simple stay for a Goa weekend.',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Cedar cabin with mountain view',
    location: 'Manali',
    pricePerNight: 4100,
    maxGuests: 3,
    amenities: ['Heating', 'Kitchen'],
    description: 'Quiet cabin above the Mall Road with snow views in winter.',
    images: ['https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Pink city courtyard haveli',
    location: 'Jaipur',
    pricePerNight: 3800,
    maxGuests: 5,
    amenities: ['WiFi', 'Courtyard'],
    description: 'Heritage rooms around a courtyard, walk to Hawa Mahal.',
    images: ['https://images.unsplash.com/photo-1477587458883-47145f127a48?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Lake-view studio',
    location: 'Udaipur',
    pricePerNight: 4500,
    maxGuests: 2,
    amenities: ['Lake view', 'AC'],
    description: 'Look over Lake Pichola from a compact studio.',
    images: ['https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Ganga-side yoga loft',
    location: 'Rishikesh',
    pricePerNight: 2200,
    maxGuests: 2,
    amenities: ['WiFi', 'Yoga mat'],
    description: 'Loft near Laxman Jhula. Easy walk to cafes and the river.',
    images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Sea-facing apartment in Bandra',
    location: 'Mumbai',
    pricePerNight: 6200,
    maxGuests: 3,
    amenities: ['AC', 'WiFi', 'Kitchen'],
    description: 'Bright flat close to Bandstand. City stay with a sea breeze.',
    images: ['https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Hauz Khas loft',
    location: 'Delhi',
    pricePerNight: 3600,
    maxGuests: 3,
    amenities: ['WiFi', 'Kitchen'],
    description: 'Industrial loft near the village cafes and the lake.',
    images: ['https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Garden cottage in Indiranagar',
    location: 'Bengaluru',
    pricePerNight: 3400,
    maxGuests: 4,
    amenities: ['Garden', 'WiFi', 'Parking'],
    description: 'Quiet cottage with a small garden, 10 minutes to MG Road.',
    images: ['https://images.unsplash.com/photo-1600596542813-5733d8e0c35e?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Backwater bungalow',
    location: 'Kochi',
    pricePerNight: 3900,
    maxGuests: 4,
    amenities: ['Backwaters', 'Kitchen'],
    description: 'Sit out over the water. Fort Kochi is a short drive.',
    images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Tea-estate bungalow',
    location: 'Darjeeling',
    pricePerNight: 4300,
    maxGuests: 4,
    amenities: ['Fireplace', 'Mountain view'],
    description: 'Wake to Kanchenjunga views and a cup of estate tea.',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Blue-city rooftop stay',
    location: 'Jodhpur',
    pricePerNight: 2800,
    maxGuests: 3,
    amenities: ['Rooftop', 'WiFi'],
    description: 'Look over the blue houses toward Mehrangarh Fort.',
    images: ['https://images.unsplash.com/photo-1477587458883-47145f127a48?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'French-quarter guesthouse',
    location: 'Pondicherry',
    pricePerNight: 3100,
    maxGuests: 2,
    amenities: ['WiFi', 'Breakfast'],
    description: 'Yellow walls, bicycles, and the promenade two streets away.',
    images: ['https://images.unsplash.com/photo-1582510003544-4d00b7f74250?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Palolem cliff resort',
    location: 'Goa',
    pricePerNight: 5400,
    maxGuests: 4,
    amenities: ['Pool', 'Sea view', 'Breakfast'],
    description: 'Pool deck looks over Palolem. Cover photo is the sunrise from the room.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Anjuna garden resthouse',
    location: 'Goa',
    pricePerNight: 2800,
    maxGuests: 3,
    amenities: ['Garden', 'WiFi'],
    description: 'Coconut shade and a private sit-out. Cover is the veranda view.',
    images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Solang valley lodge',
    location: 'Manali',
    pricePerNight: 4800,
    maxGuests: 4,
    amenities: ['Heating', 'Mountain view'],
    description: 'Window wall faces the snow line. Cover is the view from the bed.',
    images: ['https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Old Manali wooden resthouse',
    location: 'Manali',
    pricePerNight: 2600,
    maxGuests: 2,
    amenities: ['Fireplace', 'Kitchen'],
    description: 'Pine cabin with a small balcony over the Beas.',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Amber Fort view resort',
    location: 'Jaipur',
    pricePerNight: 7200,
    maxGuests: 4,
    amenities: ['Pool', 'Spa', 'Breakfast'],
    description: 'Pool looks toward the fort hills. Cover is the pool terrace.',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Bani Park heritage resthouse',
    location: 'Jaipur',
    pricePerNight: 2900,
    maxGuests: 3,
    amenities: ['Courtyard', 'WiFi'],
    description: 'Carved windows and a quiet courtyard room.',
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Pichola lake palace stay',
    location: 'Udaipur',
    pricePerNight: 8900,
    maxGuests: 2,
    amenities: ['Lake view', 'Breakfast', 'AC'],
    description: 'Cover photo is sunrise on the lake from the window seat.',
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Fateh Sagar hillside resthouse',
    location: 'Udaipur',
    pricePerNight: 3500,
    maxGuests: 3,
    amenities: ['Terrace', 'Kitchen'],
    description: 'Open terrace above the lake road.',
    images: ['https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Tapovan riverside resort',
    location: 'Rishikesh',
    pricePerNight: 4100,
    maxGuests: 3,
    amenities: ['River view', 'Yoga', 'Breakfast'],
    description: 'Cover is the Ganga from the balcony at dusk.',
    images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Laxman Jhula quiet resthouse',
    location: 'Rishikesh',
    pricePerNight: 1800,
    maxGuests: 2,
    amenities: ['WiFi', 'Garden'],
    description: 'Simple room with a garden sit-out near the bridge.',
    images: ['https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Marine Drive hotel suite',
    location: 'Mumbai',
    pricePerNight: 9800,
    maxGuests: 3,
    amenities: ['Sea view', 'AC', 'Room service'],
    description: 'Cover is the Queen’s Necklace from the suite window.',
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Juhu resthouse with palm view',
    location: 'Mumbai',
    pricePerNight: 5100,
    maxGuests: 4,
    amenities: ['Kitchen', 'WiFi'],
    description: 'Palms and a long balcony. Cover is the evening sit-out.',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Lodhi garden boutique stay',
    location: 'Delhi',
    pricePerNight: 6700,
    maxGuests: 2,
    amenities: ['Garden', 'Breakfast', 'AC'],
    description: 'Cover is the lawn and pool from the room door.',
    images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Chandni Chowk haveli resthouse',
    location: 'Delhi',
    pricePerNight: 2400,
    maxGuests: 3,
    amenities: ['WiFi', 'Courtyard'],
    description: 'Old-city courtyard room. Cover is the inner court.',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Whitefield pool villa',
    location: 'Bengaluru',
    pricePerNight: 5600,
    maxGuests: 5,
    amenities: ['Pool', 'Parking', 'Kitchen'],
    description: 'Cover is the private pool from the living room.',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Koramangala loft resthouse',
    location: 'Bengaluru',
    pricePerNight: 2700,
    maxGuests: 2,
    amenities: ['WiFi', 'Kitchen'],
    description: 'Bright loft. Cover is the mezzanine looking down.',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Vembanad lake resort',
    location: 'Kochi',
    pricePerNight: 7800,
    maxGuests: 4,
    amenities: ['Backwaters', 'Pool', 'Breakfast'],
    description: 'Cover is the lake from the cottage deck.',
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Fort Kochi spice resthouse',
    location: 'Kochi',
    pricePerNight: 2500,
    maxGuests: 2,
    amenities: ['WiFi', 'Courtyard'],
    description: 'Heritage rooms near the Chinese nets.',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Tiger Hill sunrise lodge',
    location: 'Darjeeling',
    pricePerNight: 5200,
    maxGuests: 3,
    amenities: ['Mountain view', 'Fireplace'],
    description: 'Cover is Kanchenjunga from the window at dawn.',
    images: ['https://images.unsplash.com/photo-1542314831-8fbf1cb72e3a?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Happy Valley tea resthouse',
    location: 'Darjeeling',
    pricePerNight: 3300,
    maxGuests: 2,
    amenities: ['Tea estate', 'Garden'],
    description: 'Cover is the tea rows from the porch.',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Mehrangarh cliff resort',
    location: 'Jodhpur',
    pricePerNight: 6400,
    maxGuests: 3,
    amenities: ['Fort view', 'Pool', 'Breakfast'],
    description: 'Cover is the fort from the pool deck.',
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Clock tower resthouse',
    location: 'Jodhpur',
    pricePerNight: 2100,
    maxGuests: 2,
    amenities: ['Rooftop', 'WiFi'],
    description: 'Blue lanes below. Cover is the rooftop at blue hour.',
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'White Town seafront resort',
    location: 'Pondicherry',
    pricePerNight: 5800,
    maxGuests: 3,
    amenities: ['Sea view', 'Breakfast', 'AC'],
    description: 'Cover is the promenade from the balcony.',
    images: ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Auroville garden resthouse',
    location: 'Pondicherry',
    pricePerNight: 2400,
    maxGuests: 2,
    amenities: ['Garden', 'Kitchen'],
    description: 'Quiet rooms in the trees. Cover is the garden path.',
    images: ['https://images.unsplash.com/photo-1600047509807-ba21d7c8fef3?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Calangute dune cottage',
    location: 'Goa',
    pricePerNight: 3700,
    maxGuests: 3,
    amenities: ['Beach access', 'WiFi'],
    description: 'Sand at the gate. Cover is the cottage looking toward the dunes.',
    images: ['https://images.unsplash.com/photo-1499793983690-e2da40d12ce9?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Mandrem lagoon resthouse',
    location: 'Goa',
    pricePerNight: 4300,
    maxGuests: 4,
    amenities: ['Lagoon view', 'Kitchen'],
    description: 'Cover is the still water from the deck at noon.',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Jal Mahal lakeside stay',
    location: 'Jaipur',
    pricePerNight: 4600,
    maxGuests: 3,
    amenities: ['Lake view', 'Breakfast'],
    description: 'Cover is Jal Mahal from the room terrace.',
    images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Amer stepwell resthouse',
    location: 'Jaipur',
    pricePerNight: 3100,
    maxGuests: 2,
    amenities: ['Courtyard', 'WiFi'],
    description: 'Stone rooms near Amber. Cover is the inner courtyard.',
    images: ['https://images.unsplash.com/photo-1600210492486-72479768bada?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Mattancherry spice warehouse stay',
    location: 'Kochi',
    pricePerNight: 3200,
    maxGuests: 3,
    amenities: ['Heritage', 'WiFi'],
    description: 'Old warehouse loft. Cover is the high wooden ceiling.',
    images: ['https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Cherai beach resthouse',
    location: 'Kochi',
    pricePerNight: 4100,
    maxGuests: 4,
    amenities: ['Beach', 'Kitchen'],
    description: 'Cover is the Arabian Sea from the sit-out.',
    images: ['https://images.unsplash.com/photo-1505691723518-36a5ac3b2d95?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Naggar castle-view lodge',
    location: 'Manali',
    pricePerNight: 3900,
    maxGuests: 3,
    amenities: ['Mountain view', 'Heating'],
    description: 'Cover is the valley from the window seat.',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80'],
  },
  {
    title: 'Jogini falls resthouse',
    location: 'Manali',
    pricePerNight: 2300,
    maxGuests: 2,
    amenities: ['Garden', 'Kitchen'],
    description: 'Cover is the orchard path outside the door.',
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80'],
  },
]

export const seedListingsIfEmpty = async () => {
  await Listing.updateMany({ status: { $exists: false } }, { $set: { status: 'approved' } })

  let host = await User.findOne({ email: 'seed.host@stayease.local' })
  if (!host) {
    host = await User.create({
      name: 'StayEase Host',
      email: 'seed.host@stayease.local',
      passwordHash: await bcrypt.hash('stayease123', 10),
      role: 'host',
    })
  }

  let added = 0
  for (const item of SEED_LISTINGS) {
    const exists = await Listing.findOne({ title: item.title, location: item.location })
    if (exists) continue
    await Listing.create({ ...item, hostId: host._id, status: 'approved' })
    added += 1
  }

  if (added > 0) console.log(`Seeded ${added} listings`)
}
